<?xml version="1.0"?>
<package format="3">
  <name>tb3_slam_mapper</name>
  <version>0.0.1</version>
  <description>Occupancy grid SLAM mapper using log-odds and Bresenham ray casting.</description>
  <maintainer email="student@example.com">student</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>ament_index_python</depend>
  <depend>geometry_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>nav_msgs</depend>
  <depend>rclpy</depend>
  <depend>rviz2</depend>
  <depend>sensor_msgs</depend>
  <depend>turtlebot3_gazebo</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
